name: CI/CD Flask App

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create dummy .env file
      run: |
        echo "DATABASE_URL=mysql+pymysql://root:root@db/mydatabase" > .env
        echo "SECRET_KEY=dummytoken" >> .env
        echo "JWT_SECRET_KEY=dummyjwt" >> .env
        echo "JWT_ACCESS_TOKEN_EXPIRES=3600" >> .env
        echo "FLASK_ENV=development" >> .env

    - name: Run tests
      run: |
        pytest tests/ --cov=app --cov-report=term-missing

  deploy-simulate:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Simulate Deployment
      run: |
        echo "Déploiement simulé : L'application serait déployée ici si tout était vert ! 🚀"
